name: Deploy Vite Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        # Note: We are running this from the ROOT now to find those missing libraries

      - name: Build
        run: pnpm run build --filter ./artifacts/**
        env:
          CI: false
          VITE_SKIP_TYPECHECK: true
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './artifacts/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
